version: "3.7"
services:
  backend:
    container_name: lrlp-back
    build:
      context: ./backend
      dockerfile: Dockerfile
    command: sh -c "composer install && cp .env.example .env && php artisan migrate && php artisan serve --host=0000"
    environment:
      DB_HOST: db
      DB_DATABASE: lumen
      DB_USERNAME: user
      DB_PASSWORD: pass
    ports:
      - 8000:8000
    volumes:
      - ./backend:/app/backend
    depends_on:
      - db
    networks:
      - app
  frontend:
    container_name: lrlp-front
    build:
      context: ./frontend
      dockerfile: Dockerfile
    command: sh -c "npm install && npm start"
    tty: true
    ports:
      - 3000:3000
    volumes:
      - ./frontend:/app/frontend
    depends_on:
      - backend
    networks:
      - app
  db:
    image: mysql:5.7.22
    container_name: lrlp-db
    tty: true
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: "lumen"
      MYSQL_USER: "user"
      MYSQL_PASSWORD: "pass"
      MYSQL_ROOT_PASSWORD: "pass"
    networks:
      - app

networks:
  app:
    driver: bridge
